---

- name: Trabajr con volumenes logicos
  hosts: rocky2
  become: true

  tasks:

  - name: Crear un volumen logico en el grupo1
    community.general.lvol:
      vg: grupo1
      lv: vol1
      size: 512

  - name: Recuperar informacion
    ansible.builtin.shell:
      cmd: 'lvdisplay | grep "LV Name"'
    register: datos

  - name: Visualizar la informacion
    debug:
      var: datos 
