---

- name: Trabajar con el módulo parted
  hosts: worker1
  become: true

  tasks:

  - name: Ver informacion de sdb
    community.general.parted:
      device: /dev/sdb
      state: info

    register: datos

  - name: Ver los datos
    debug:
      var: datos
