---
- name: Practica de tagss
  hosts: all
  become: true
  
  tasks:
  - name: Instalar Apache Ubuntu
    ansible.builtin.apt:
      name: apache2
      state: present
    when: ansible_facts['distribution']=="Ubuntu"
    tags:
      - Ubuntu

  - name: Instalar Apache Rocky
    ansible.builtin.yum:
      name: httpd
      state: present
    when: ansible_facts['distribution']=="Rocky"
    tags:
      - Rocky

  - name: Arrancar Apache Ubuntu
    service:
      name: apache2
      state: started
    when: ansible_facts['distribution']=="Ubuntu"
    tags:
      - Ubuntu

  - name: Arrancar Apache Rocky
    service:
      name: httpd
      state: started
    when: ansible_facts['distribution']=="Rocky"
    tags:
      - Rocky
  
  - name: Copiar archivo html Ubuntu
    ansible.builtin.copy:
      src: index_debian.html
      dest: /var/www/html/index.html
    when: ansible_facts['distribution']=="Ubuntu"
    tags:
      - Ubuntu

  - name: Copiar archivo html Rocky
    ansible.builtin.copy:
      src: index_rocky.html
      dest: /var/www/html/index.html
    when: ansible_facts['distribution']=="Rocky"
    tags:
      - Rocky

  - name: Ultima tarea
    ansible.builtin.debug:
      msg: "Proceso terminado"
    tags:
      - always


