---
- name: Descargar imagen Docker
  hosts: ubuntu
  become: true

  tasks:

  - name: Crear un contenedor con Busybox
    community.docker.docker_container:
      name: contenedor1
      image: busybox
      state: started
