---

- name: Prueba con variables
  hosts: worker1
  
  tasks:
  - name: Variable local
    vars:
      v1: "Prueba"
    debug:
      msg: "Este valor es local {{v1}}"

  - name: Variable que viene del inventario
    debug:
      msg: "Este valor es local {{v2}}"
